<a href="https://colab.research.google.com/github/devyadav11/ML_tryouts/blob/main/Notes_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch.nn as nn
import torch.optim as optim

import pandas as pd
import math
import torch
import torchvision
import torch.nn.functional as F  # Parameterless functions, like (some) activation functions
import torchvision.datasets as datasets  # Standard datasets
import torchvision.transforms as transforms  # Transformations we can perform on our dataset for augmentation
from torch import optim  # For optimizers like SGD, Adam, etc.
from torch import nn  # All neural network modules
from torch.utils.data import ( DataLoader, random_split)                    # Gives easier dataset managment by creating mini batches etc.
from tqdm import tqdm                                                       # For nice progress bar!

from torchvision.datasets import ImageFolder
import os
import random
import matplotlib.pyplot as plt
import numpy as np
import pathlib

In [2]:
# 1.  zip = combine multiple iterables (like lists or tuples) element-wise into tuples. It's like pairing items together by their positions.

a = [1, 2, 3]
b = ['a', 'b', 'c']

zipped = zip(a, b)
print(list(zipped))

for num, char in zip(a, b):
    print(num, char)



[(1, 'a'), (2, 'b'), (3, 'c')]
1 a
2 b
3 c


Dictionary: {}

In [51]:
# ''.items ====>  it takes dictionary key,value pairs and create tupels of it.
z = {'a': 1, 'b': 2, 'c': 3}
print(z.items())

dict_items([('a', 1), ('b', 2), ('c', 3)])


In [3]:
words = open('names.txt', 'r').read().splitlines()
print(words[:10])

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia', 'harper', 'evelyn']


In [8]:
b = {}
for w in words:
  chs = ['<s>'] + list(w) + ['<e>']
  for ch1, ch2 in zip(chs, chs[1:]):
    bigram = (ch1, ch2)
    b[bigram] = b.get(bigram, 0) + 1

print(b)

{('<s>', 'e'): 1531, ('e', 'm'): 769, ('m', 'm'): 168, ('m', 'a'): 2590, ('a', '<e>'): 6640, ('<s>', 'o'): 394, ('o', 'l'): 619, ('l', 'i'): 2480, ('i', 'v'): 269, ('v', 'i'): 911, ('i', 'a'): 2445, ('<s>', 'a'): 4410, ('a', 'v'): 834, ('v', 'a'): 642, ('<s>', 'i'): 591, ('i', 's'): 1316, ('s', 'a'): 1201, ('a', 'b'): 541, ('b', 'e'): 655, ('e', 'l'): 3248, ('l', 'l'): 1345, ('l', 'a'): 2623, ('<s>', 's'): 2055, ('s', 'o'): 531, ('o', 'p'): 95, ('p', 'h'): 204, ('h', 'i'): 729, ('<s>', 'c'): 1542, ('c', 'h'): 664, ('h', 'a'): 2244, ('a', 'r'): 3264, ('r', 'l'): 413, ('l', 'o'): 692, ('o', 't'): 118, ('t', 't'): 374, ('t', 'e'): 716, ('e', '<e>'): 3983, ('<s>', 'm'): 2538, ('m', 'i'): 1256, ('a', 'm'): 1634, ('m', 'e'): 818, ('<s>', 'h'): 874, ('r', 'p'): 14, ('p', 'e'): 197, ('e', 'r'): 1958, ('r', '<e>'): 1377, ('e', 'v'): 463, ('v', 'e'): 568, ('l', 'y'): 1588, ('y', 'n'): 1826, ('n', '<e>'): 6763, ('b', 'i'): 217, ('i', 'g'): 428, ('g', 'a'): 330, ('a', 'i'): 1650, ('i', 'l'): 1345,

In [5]:
x = torch.Generator().manual_seed(12345)  # fixes the random numbers
g = torch.rand(1,5, generator=x)
g = g/g.sum()
print(g)
g.float()

tensor([[0.2889, 0.2589, 0.2920, 0.1357, 0.0245]])


tensor([[0.2889, 0.2589, 0.2920, 0.1357, 0.0245]])

In [6]:
g = torch.multinomial(g, num_samples = 10, replacement=True, generator = x)
g

tensor([[1, 1, 2, 1, 0, 2, 2, 1, 1, 3]])

In [19]:
characters = sorted(list(set(''.join(words))))
print(characters)


['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [29]:
c2i = {c:i+1 for i,c in enumerate(characters)}
c2i['.'] = 0
i2c = {i:c for c,i in c2i.items()}      # It returns a view of the dictionary’s key-value pairs as tuples

print(c2i)
print(i2c)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10, 'k': 11, 'l': 12, 'm': 13, 'n': 14, 'o': 15, 'p': 16, 'q': 17, 'r': 18, 's': 19, 't': 20, 'u': 21, 'v': 22, 'w': 23, 'x': 24, 'y': 25, 'z': 26, '.': 0}
{1: 'a', 2: 'b', 3: 'c', 4: 'd', 5: 'e', 6: 'f', 7: 'g', 8: 'h', 9: 'i', 10: 'j', 11: 'k', 12: 'l', 13: 'm', 14: 'n', 15: 'o', 16: 'p', 17: 'q', 18: 'r', 19: 's', 20: 't', 21: 'u', 22: 'v', 23: 'w', 24: 'x', 25: 'y', 26: 'z', 0: '.'}


In [76]:
N = torch.zeros(27,27).float()
b = 0
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = c2i[ch1]
    ix2 = c2i[ch2]
    N[ix1, ix2] += 1
    b += 1
print(N)
print(b)

tensor([[0.0000e+00, 4.4100e+03, 1.3060e+03, 1.5420e+03, 1.6900e+03, 1.5310e+03,
         4.1700e+02, 6.6900e+02, 8.7400e+02, 5.9100e+02, 2.4220e+03, 2.9630e+03,
         1.5720e+03, 2.5380e+03, 1.1460e+03, 3.9400e+02, 5.1500e+02, 9.2000e+01,
         1.6390e+03, 2.0550e+03, 1.3080e+03, 7.8000e+01, 3.7600e+02, 3.0700e+02,
         1.3400e+02, 5.3500e+02, 9.2900e+02],
        [6.6400e+03, 5.5600e+02, 5.4100e+02, 4.7000e+02, 1.0420e+03, 6.9200e+02,
         1.3400e+02, 1.6800e+02, 2.3320e+03, 1.6500e+03, 1.7500e+02, 5.6800e+02,
         2.5280e+03, 1.6340e+03, 5.4380e+03, 6.3000e+01, 8.2000e+01, 6.0000e+01,
         3.2640e+03, 1.1180e+03, 6.8700e+02, 3.8100e+02, 8.3400e+02, 1.6100e+02,
         1.8200e+02, 2.0500e+03, 4.3500e+02],
        [1.1400e+02, 3.2100e+02, 3.8000e+01, 1.0000e+00, 6.5000e+01, 6.5500e+02,
         0.0000e+00, 0.0000e+00, 4.1000e+01, 2.1700e+02, 1.0000e+00, 0.0000e+00,
         1.0300e+02, 0.0000e+00, 4.0000e+00, 1.0500e+02, 0.0000e+00, 0.0000e+00,
         8.4200e+

In [97]:
p = N/N.sum(1, keepdims=True)
print(p[0].sum())

tensor(1.)


In [101]:
x = torch.Generator().manual_seed(12345)  # fixes the random numbers

for i in range(10):
  starting = 0
  predicted_word = []
  while True:
    p = N[starting].float()

    #p = torch.ones(27)
    #p = p/p.sum()
    starting = torch.multinomial(p, num_samples=1, replacement=True, generator=x).item()
    next_char = i2c[starting]
    if next_char == '.':
      break
    predicted_word.append(next_char)

  print(''.join(predicted_word))

jun
dononchuligeinnge
ayayzl
lul
a
itvelyanadahrerim
lan
betshobeen
heeon
th
